title: Scheme Decyder
description: A miniature painting, RPG, and programming blog. Hopefully with some intersections of the three.
author:
  name: Decyne
github_username: scheme-decyder

remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
