title: Scheme Decyder
description: A miniature painting, RPG blog. Occasionally with some programming intersections.
author: Decyne
github_username: scheme-decyder

remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
